NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.\
It is the fundamental package for scientific computing with Python

In [2]:
import numpy as np
my_lst=[1,2,3,4,5]

In [3]:
arr=np.array(my_lst)
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[10,20,20,40,50]
arr=np.array([my_lst1,my_lst2])
arr

array([[ 1,  2,  3,  4,  5],
       [10, 20, 20, 40, 50]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(2, 5)

# ARRAY INDEXING

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [10, 20, 20, 40, 50]])

In [9]:
arr[1,2]

20

In [29]:
print(arr[1,2]+arr[0,4])

25


# ARRAY SLICING

In [25]:
#2nd row
arr[1:,]

array([[10, 20, 20, 40, 50]])

In [26]:
#1st Row
arr[0]

array([1, 2, 3, 4, 5])

In [22]:
arr[0:,]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 20, 40, 50]])

In [27]:
#3rd column
arr[:,2]

array([ 3, 20])

In [30]:
arr[::2]

array([[1, 2, 3, 4, 5]])

In [31]:
print(arr[1, 1:4])

[20 20 40]


In [32]:
print(arr[0, 0:4])

[1 2 3 4]


In [33]:
print(arr[0, 1:4])

[2 3 4]


In [34]:
print(arr[0:2, 2])

[ 3 20]


In [35]:
print(arr[0:2, 1:4])

[[ 2  3  4]
 [20 20 40]]


In [12]:
arr[arr<=5]

array([1, 2, 3, 4, 5])

In [13]:
arr[arr<=20]

array([ 1,  2,  3,  4,  5, 10, 20, 20])

In [14]:
arr[arr!=20]

array([ 1,  2,  3,  4,  5, 10, 40, 50])

In [16]:
arr[arr>=20]

array([20, 20, 40, 50])

# SHAPE & RESHAPE

In [17]:
arr1=np.arange(0,10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
arr2=np.arange(0,10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
a = np.arange(0,12)

newarr = a.reshape(2, 3, 2)

print(newarr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [41]:
newarr.dtype

dtype('int32')

In [42]:
newarr.shape

(2, 3, 2)

In [43]:
newarr[0,0,0]

0

In [44]:
newarr[1,1,1]

9

In [45]:
b= np.arange(0,100)
narr = b.reshape(2,50)
narr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [47]:
narr[1,49]

99

In [48]:
narr[0,49]

49

In [54]:
#Converting an n-d array into 1d

In [50]:
xy = narr.reshape(-1)
print(xy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# ITERARTING ON ARRAYS

In [55]:
for x in my_lst1:
    print(x)

1
2
3
4
5


In [56]:
for x in my_lst2:
    print(x)

10
20
20
40
50


In [57]:
for x in arr:
    print(x)

[1 2 3 4 5]
[10 20 20 40 50]


In [58]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
10
20
20
40
50


In [59]:
for x in np.nditer(arr2):
  print(x)

0
1
2
3
4
5
6
7
8
9


# SPLIITING ARRAYS

In [61]:
sparr = np.array_split(my_lst,2)

print(sparr)

[array([1, 2, 3]), array([4, 5])]


In [62]:
sparr1 = np.array_split(my_lst1,2)

print(sparr1)

[array([1, 2, 3]), array([4, 5])]


In [63]:
sparr2 = np.array_split(my_lst2,2)

print(sparr2)

[array([10, 20, 20]), array([40, 50])]


In [64]:
x= np.random.randint(100)

In [65]:
x

48

In [66]:
np.random.rand(3,3)

array([[0.52612241, 0.25345228, 0.37179636],
       [0.0611985 , 0.47125007, 0.22933375],
       [0.35290885, 0.83315499, 0.5346821 ]])

In [67]:
np.random.randn(4,4)

array([[ 0.087859  ,  2.13216983,  1.31101814, -0.89016559],
       [ 1.31946061,  0.76835374, -0.68145549, -1.76639984],
       [ 1.96240609,  0.27749644, -0.26882007, -0.63881112],
       [-0.5242883 , -0.74248907,  1.5666954 , -0.97258751]])